name: Force build DllRegister
on:
  workflow_dispatch:
    inputs:
      publishEnabled:
        description: "Publish to Nuget.org"
        type: boolean
        required: false
        default: false

env:
  nugetOutputPath: ${{  'nupkgs'  }}

jobs:
  build_and_publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version:
            3.1.x
            6.x
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: "6.x"
      - name: Generate NuGet packages
        id: build_nugets
        run: |
          cd ./Generator
          ./Evergine.DllRegister/Generate-NuGets.ps1 -csprojPath Evergine.DllRegister\Evergine.DllRegister.csproj -outputfolder ${{  env.nugetOutputPath  }}
      - name: Publish NuGet
        shell: pwsh
        if: ${{ success() && github.event.inputs.publishEnabled == 'true' }}
        env:
          token: ${{secrets.EVERGINE_NUGETORG_TOKEN}}
        run: |
          cd ./Generator/${{  env.nugetOutputPath  }}
          dotnet nuget push "**/*.nupkg" --skip-duplicate --no-symbols -k "$env:token" -s https://api.nuget.org/v3/index.json
      - name: SendGrid Mail Action
        if: ${{ failure() }}
        uses: mmichailidis/sendgrid-mail-action@v1.1
        with:
          # The token for sendgrid
          sendgrid-token: ${{ secrets.WAVE_SENDGRID_TOKEN }}
          # List of emails separated by comma that the email will go
          mail: ${{ secrets.EVERGINE_EMAILREPORT_LIST }}
          # The email that will be shown as sender
          from: ${{ secrets.EVERGINE_EMAIL }}
          # The subject of the email
          subject: Imgui Update NuGet has failed
          # Defines if it should be one email with multiple address or multiple emails with a single address
          individual: false
          # The body of the mail. The placeholders that can be used are $EVENT$, $ISSUE$, $ACTION$
          text: something when wrong when updating Imgui bindings
